### ISSUE TITLE
Todo for Rob

### ISSUE THREAD

**Issue by marchershey** [marchershey/lodget-old#1]
### Things I need...
- [ ] Privacy Policy
- [ ] Terms of Service
- [ ] Reservation Agreement
- [ ] Cancellation Policy

### Things to go over...
**What kind of signature to use?**
- [ ] Simple and personal - such as "Thanks, Rob & Erin Serrate" or just "Rob Serrate"
- [ ] Professional, corporate style -  "Thanks, Serrate Rentals Team"
